Rework/lazy load
SNWCreations/KookBC pull request #100
Opened 2024-08-25 14:35 UTC by natholdallas

2024-08-25 15:05 UTC, huanmeng-qwq requested changes

2024-08-25 15:05 UTC, huanmeng-qwq commented on src/main/java/snw/kookbc/impl/launch/LaunchClassLoader.java
> +public class LaunchClassLoader extends URLClassLoader implements AccessClassLoader {
这里为什么移除MarkedClassLoader接口？

2024-08-25 15:22 UTC, natholdallas commented on src/main/java/snw/kookbc/impl/launch/LaunchClassLoader.java
> +public class LaunchClassLoader extends URLClassLoader implements AccessClassLoader {
AccessClassLoader 接口继承了 MarkedClassLoader, 虽然不在 lazyload 的范畴中, 但是夏夜有批准可以执行部分的 clean code 工作

2024-08-25 15:26 UTC, huanmeng-qwq commented on src/main/java/snw/kookbc/impl/launch/LaunchClassLoader.java
> +public class LaunchClassLoader extends URLClassLoader implements AccessClassLoader {
Approve.

2024-08-25 15:58 UTC, SNWCreations requested changes
Still need change.

2024-08-25 15:58 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/HttpAPIImpl.java
> -                        "cloudmusic", "qqmusic", "kugou"
对于这些常量，不应该代码格式化。旧有写法是刻意为之。

2024-08-25 15:58 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/HttpAPIImpl.java
> -            long contentLength = body.contentLength();
不应该对被注释的代码格式化，我们可能随时会重新启用它们。

2024-08-25 15:58 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/entity/CustomEmojiImpl.java
> -        // optional attributes are following:
注释的位置不应该变动。

2024-08-25 15:58 UTC, SNWCreations commented on src/main/java/snw/kookbc/interfaces/LazyLoadable.java
> +    default void lazyload() {
新的方法名不如旧的语义清楚。

2024-08-25 15:58 UTC, SNWCreations commented on src/main/java/snw/kookbc/util/GsonUtil.java
> +    public static JsonNull getAsJsonNull(JsonObject object, String key) {
项目中并不使用 json null ，此方法似乎不必要。

2024-08-25 16:28 UTC, natholdallas commented on src/main/java/snw/kookbc/util/GsonUtil.java
> +    public static JsonNull getAsJsonNull(JsonObject object, String key) {
already modify and pushed, plz check

2024-08-25 19:04 UTC, SNWCreations commented
Still something not resolved yet

2024-08-27 06:19 UTC, SNWCreations approved these changes
OK

2024-08-27 06:22 UTC, SNWCreations commented
在其他reviewer批准后此PR即可合并。

2024-08-27 06:35 UTC, huanmeng-qwq approved these changes

2024-08-27 06:48 UTC, xiaoACE6716 approved these changes

2024-08-27 06:49 UTC, DAYGoodTime commented
兜兜转转，终于结束了。

2024-08-27 06:51 UTC, merged