实现 remake/event-deserialize 内容
SNWCreations/KookBC pull request #29
Opened 2023-04-03 15:00 UTC by NatholDallas

hello 各位开发者
这是我实现的 remake/event-deserialize
请参阅

2023-04-03 16:29 UTC, huanmeng-qwq requested changes
请在每个类文件的头部添加版权声明

2023-04-04 02:53 UTC, xiaoACE6716 commented on src/main/java/snw/kookbc/impl/event/EventFactory2.java
可以缩短import 比如改成`import snw.jkook.event.channel.*;`

2023-04-04 03:19 UTC, xiaoACE6716 commented on src/main/java/snw/kookbc/impl/serializer/event/guild/GuildAddEmojiEventDerserializer.java
> +        CustomEmoji emoji1 = client.getEntityBuilder().buildEmoji(body);
这里没有更多的CustomEmoji对象，为什么变量名要叫emoji1呢

2023-04-04 03:22 UTC, xiaoACE6716 commented on src/main/java/snw/kookbc/impl/serializer/event/guild/GuildRemoveEmojiEventDerserializer.java
> +        CustomEmoji emoji2 = client.getStorage().getEmoji(body.get("id").getAsString(), body);
这里没有更多的CustomEmoji对象，为什么变量名要叫emoji2呢

2023-04-04 03:23 UTC, xiaoACE6716 commented on src/main/java/snw/kookbc/impl/serializer/event/guild/GuildUpdateEmojiEventDerserializer.java
> +        CustomEmoji emoji3 = client.getStorage().getEmoji(body.get("id").getAsString(), body);
这里没有更多的CustomEmoji对象，为什么变量名要叫emoji3呢

2023-04-04 03:30 UTC, xiaoACE6716 requested changes
是不是还少了 PrivateMessageReceivedEvent 和 UserAddReactionEvent，等夏夜也来review一遍吧

2023-04-05 01:42 UTC, SNWCreations requested changes
见详细内容。
另外，大多数新类名称拼写错误。是 Deserializer ，不是 De**r**serializer 。

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/pm/PrivateMessageDeleteEventDerserializer.java
> +        client.getStorage().removeMessage(body.get("msg_id").getAsString());
这一行可以分离到 beforeReturn

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/channel/ChannelMessageUpdateEventDeserializer.java
> +                body.get("content").getAsString()
content 应该同步到相应消息对象...这个我来做

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/role/RoleCreateEventDerserializer.java
> +        Role role = client.getEntityBuilder().buildRole(
这个 role 没有在 beforeReturn 里添加进 Storage ...我来做

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/role/RoleDeleteEventDerserializer.java
> +        Role deletedRole = client.getEntityBuilder().buildRole(
应该先检查 storage ，如果没有，再构造一次性对象。我来做

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/user/UserRemoveReactionEventDerserializer.java
> +        Reaction reaction1 = client.getStorage().getReaction(
这里没有更多 reaction...

2023-04-05 01:42 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/serializer/event/user/UserRemoveReactionEventDerserializer.java
> +            reaction1 == null ? new ReactionImpl(
可以优化，我来做

2023-04-05 02:35 UTC, NatholDallas commented on src/main/java/snw/kookbc/impl/serializer/event/user/UserRemoveReactionEventDerserializer.java
> +            reaction1 == null ? new ReactionImpl(
Optional?

2023-04-05 04:15 UTC, NatholDallas commented on src/main/java/snw/kookbc/impl/serializer/event/guild/GuildDeleteEventDerserializer.java
> +    protected GuildDeleteEvent deserialize(JsonObject object, Type type, JsonDeserializationContext ctx, long timeStamp, JsonObject body) throws JsonParseException {
请问这里需不需要将Guild移除?我不确定他是否需要移植到beforeReturn中

2023-04-05 04:21 UTC, NatholDallas commented on src/main/java/snw/kookbc/impl/serializer/event/guild/GuildUpdateEmojiEventDerserializer.java
> +        CustomEmoji emoji3 = client.getStorage().getEmoji(body.get("id").getAsString(), body);
已经解决此问题,请等待我的push

2023-04-05 04:31 UTC, NatholDallas commented on src/main/java/snw/kookbc/impl/serializer/event/channel/ChannelInfoUpdateEventDeserializer.java
> +                    body.get("id").getAsString());
请问这个地方需要放置在beforReturn中吗

2023-04-05 04:36 UTC, NatholDallas commented on src/main/java/snw/kookbc/impl/serializer/event/channel/ChannelMessageUpdateEventDeserializer.java
> +                body.get("content").getAsString()
好的

2023-04-05 06:30 UTC, SNWCreations commented
目前确定无其他问题。另要求: 将所有的 beforeReturn 方法的 event 参数统一重命名为 event 。
审核仍在继续。

2023-04-05 09:07 UTC, SNWCreations reviewed
代码可以开始优化。

2023-04-05 09:51 UTC, SNWCreations approved these changes
可以合并。

2023-04-05 11:27 UTC, xiaoACE6716 approved these changes
暂无更多意见

2023-04-07 13:29 UTC, huanmeng-qwq approved these changes

2023-04-08 01:07 UTC, merged