第二代事件构造器
SNWCreations/KookBC pull request #42
Opened 2023-05-01 05:26 UTC by SNWCreations

# KookBC Pull Request

重写了 KookBC 的事件构造器。

主要工作由 @NatholDallas 完成，我完成校对与漏洞修复。

2023-05-01 12:08 UTC, xiaoACE6716 approved these changes
测了几个我个人觉得使用率高的事件都没问题

2023-05-01 12:24 UTC, xiaoACE6716 requested changes
监听按钮点击事件拿不到频道对象

2023-05-02 02:06 UTC, SNWCreations commented
可以继续审核。

2023-05-02 08:36 UTC, xiaoACE6716 approved these changes

2023-05-27 05:27 UTC, merged