Feat/command cloud
SNWCreations/KookBC pull request #49
Opened 2023-06-14 18:20 UTC by huanmeng-qwq

# KookBC Pull Request

## 增加的新内容

### 对Cloud CommandFramework添加支持
- 新增`@CommandPrefix`注解支持对指令添加多个prefix
- 自动注入`Message`类型的`形参`, 没有则null
- 支持直接将JKookCommand的指令接入
- 自动创建指令对象时支持`Plugin`参数

2023-06-16 07:19 UTC, SNWCreations commented
请给出测试代码。

2023-06-16 07:58 UTC, SNWCreations commented
NullMessage 在当前的代码中从未使用。如果最终代码不再使用，请移除它。
请考虑与 dev 上游进行一次 merge 以同步最新进度

2023-06-16 09:19 UTC, huanmeng-qwq commented
> 请给出测试代码。

直接启动即可, `CloudHelpCommand`指令将被注册, 可以在控制台输入以下内容: #help、-help、$help、help进行测试是否能够正常调用`CloudHelpCommand#consoleHelp`方法

2023-06-16 09:50 UTC, SNWCreations commented
请等待测试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月16日(周五) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




  
请给出测试代码。
  
直接启动即可, CloudHelpCommand指令将被注册, 可以在控制台输入以下内容: #help、-help、$help、help进行测试是否能够正常调用CloudHelpCommand#consoleHelp方法
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-20 05:40 UTC, SNWCreations commented
不通过。纯 JKook 命令不能工作，虽然可以被 /help 命令发现，但是无法调用。通过 Cloud 方式注册的命令也没有出现在 /help 的结果中。

2023-06-20 05:40 UTC, SNWCreations requested changes
See comments

2023-06-21 01:22 UTC, SNWCreations commented
JKook 命令现在可以工作，但是在控制台时命令前缀应该被忽略。

2023-06-21 01:22 UTC, SNWCreations requested changes
See comments

2023-06-23 13:19 UTC, huanmeng-qwq commented
```shell
> /help
[21:17:08] [Main Thread/INFO]: Console issued command: /help
[21:17:08] [Main Thread/INFO]: Unknown command. Type "/help" for help.
> help
[21:17:09] [Main Thread/INFO]: Console issued command: help
[21:17:09] [Main Thread/INFO]: -------- 命令帮助 --------
[21:17:09] [Main Thread/INFO]: (/)stop: 停止 KookBC 实例。
[21:17:09] [Main Thread/INFO]: ($ - #)help: 此命令没有简介。
[21:17:09] [Main Thread/INFO]: (/)plugins: 获取已安装到此 KookBC 实例的插件列表。
[21:17:09] [Main Thread/INFO]: 
[21:17:09] [Main Thread/INFO]: 注: 在每条命令帮助的开头，括号中用空格隔开的字符为此命令的前缀。
[21:17:09] [Main Thread/INFO]: 如 "(/ .)blah" 即 "/blah", ".blah" 为同一条命令。
[21:17:09] [Main Thread/INFO]: -------------------------
> /plugins
[21:17:29] [Main Thread/INFO]: Console issued command: /plugins
[21:17:29] [Main Thread/INFO]: Installed and running plugins (1): TestPlugin
> plugins
[21:17:31] [Main Thread/INFO]: Console issued command: plugins
[21:17:31] [Main Thread/INFO]: Installed and running plugins (1): TestPlugin
> 
```

2023-06-23 13:21 UTC, SNWCreations commented
收到了，明天测试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




 
@huanmeng-qwq requested your review on: #49 基于 Cloud 库的命令系统.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-23 13:27 UTC, SNWCreations commented
另附: 如果可能，请考虑让通过 Cloud API 注册的命令可以出现在 /help 命令的结果。
这一点之前提过，但我好像没看见相关代码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




 
@huanmeng-qwq requested your review on: #49 基于 Cloud 库的命令系统.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-23 14:10 UTC, huanmeng-qwq commented
> 另附: 如果可能，请考虑让通过 Cloud API 注册的命令可以出现在 /help 命令的结果。 这一点之前提过，但我好像没看见相关代码。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月23日(周五) 晚上9:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"Review ***@***.***&gt;; 主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49) @huanmeng-qwq requested your review on: #49 基于 Cloud 库的命令系统. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because your review was requested.Message ID: ***@***.***&gt;

CloudHelpCommand#buildHelpContent已经使用CloudCommandInfo实现了

2023-06-23 14:11 UTC, SNWCreations commented
收到，剩余的测试将在明天进行。我需要休息了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 晚上10:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




  
另附: 如果可能，请考虑让通过 Cloud API 注册的命令可以出现在 /help 命令的结果。 这一点之前提过，但我好像没看见相关代码。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年6月23日(周五) 晚上9:20 收件人: @.&gt;; 抄送: @.&gt;;"Review @.&gt;; 主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49) @huanmeng-qwq requested your review on: #49 基于 Cloud 库的命令系统. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because your review was requested.Message ID: @.***&gt;
  
CloudHelpCommand#buildHelpContent已经使用CloudCommandInfo实现了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-25 12:26 UTC, SNWCreations approved these changes
通过。但是暂不合并。待 DeeChael 的 Help PR (#48) 合并后需要同步将帮助内容更新为卡片样式的。

2023-06-25 14:10 UTC, SNWCreations commented
现在请同步上游

2023-06-25 15:45 UTC, huanmeng-qwq commented
ok

2023-06-26 02:14 UTC, SNWCreations commented
感觉可以移除 CloudHelpCommand 上的除 / 外的其他前缀。并且可以修改 KBCClient.registerHelpCommand ，如果 Cloud 启用，使用 CloudHelpCommand 而不是原生 Help



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月25日(周日) 晚上11:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




 
ok
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-26 02:45 UTC, huanmeng-qwq commented
> 感觉可以移除 CloudHelpCommand 上的除 / 外的其他前缀。并且可以修改 KBCClient.registerHelpCommand ，如果 Cloud 启用，使用 CloudHelpCommand 而不是原生 Help
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月25日(周日) 晚上11:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"Review ***@***.***&gt;; 主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49) ok — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because your review was requested.Message ID: ***@***.***&gt;

snw/kookbc/impl/KBCClient.java:496 已经是判断`如果 Cloud 启用`的了

2023-06-26 04:45 UTC, huanmeng-qwq commented
done

2023-06-26 07:00 UTC, SNWCreations commented
请清理 Javadoc (可以保留 author 项)。
错误的执行者类型反馈信息中，"玩家"应该改为"KOOK 用户"。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月26日(周一) 中午12:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




 
done
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-26 07:47 UTC, SNWCreations commented
暂无其他修改意见，请检查代码。
计划于明天合并。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月26日(周一) 中午12:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Review ***@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 基于 Cloud 库的命令系统 (PR #49)




 
done
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-06-27 05:06 UTC, SNWCreations commented
检查时发现 CloudCommandRegistrationHandlerImpl 类从未使用。如果其不再使用，请移除。并请顺便检查其他新加入的类是否有未使用的，若有且类不再有用，一并移除。

2023-06-27 05:15 UTC, huanmeng-qwq commented
`CloudCommandRegistrationHandlerImpl`最初设计的目的是以jkookcommand为主，有 cloud注册的指令将被封装为jkookcommand进行注册，后经提议改为以cloud为主, 则该类一直没有被使用

2023-06-27 05:20 UTC, SNWCreations commented
已确认 JKook 标准命令与 Cloud 命令 (/help) 可以运作。此类可以安全移除了。

2023-06-27 05:26 UTC, SNWCreations approved these changes
OK

2023-06-27 05:26 UTC, SNWCreations commented
可以合并。

2023-06-27 05:39 UTC, SNWCreations commented
撤回可合并操作。新问题：JKook 标准命令不能通过 CommandMap#unregister 方法正确注销。

2023-06-27 05:39 UTC, SNWCreations requested changes
see comments

2023-06-27 05:40 UTC, SNWCreations commented
CommandMap#unregister 出现异常。正在解决。

2023-06-27 05:43 UTC, SNWCreations commented
现在可以合并。

2023-06-27 05:45 UTC, SNWCreations approved these changes
OK

2023-06-27 05:45 UTC, merged