修复旧版命令系统的命令在执行时不在控制台打印日志的问题
SNWCreations/KookBC pull request #53
Opened 2023-07-21 13:15 UTC by xiaoACE6716

# KookBC Pull Request

您的 Fork 仓库地址:https://github.com/xiaoACE6716/KookBC

## 增加的新内容

修复旧版命令系统的命令在执行时不在控制台打印日志的问题。

2023-07-21 13:17 UTC, SNWCreations commented
尽量使用 KBCClient 的 core 的 logger ，为嵌入环境考虑。

2023-07-22 01:24 UTC, xiaoACE6716 commented
> 尽量使用 KBCClient 的 core 的 logger ，为嵌入环境考虑。

我看在下面的代码幻梦用的也是  `JKook.getCore().getLogger()` 我才用的这个

2023-07-23 02:22 UTC, SNWCreations commented
> > 尽量使用 KBCClient 的 core 的 logger ，为嵌入环境考虑。
> 
> 我看在下面的代码幻梦用的也是 `JKook.getCore().getLogger()` 我才用的这个

我将检查相关代码并纠正。

2023-07-24 09:33 UTC, SNWCreations requested changes
现有代码不能正确判断输入消息是不是命令（即使是普通聊天消息也会输出 issued command）
另外，"The execution of command line ... is done/FAILED" 位置不正确。应当在命令结束后，但是出现在命令开始执行前（甚至是 issued command 之前）

2023-07-25 03:02 UTC, SNWCreations approved these changes
OK

2023-07-25 03:03 UTC, merged