改用LiteCommand命令框架
SNWCreations/KookBC pull request #63
Opened 2024-02-12 14:26 UTC by huanmeng-qwq

2024-02-12 16:14 UTC, huanmeng-qwq commented on src/main/java/snw/kookbc/impl/command/litecommands/tools/KookMessageContextual.java
> +        } catch (NullPointerException ignored) {
[LiteCommands#373](https://github.com/Rollczi/LiteCommands/pull/373) 修复 等待发版之后更改

2024-02-12 16:14 UTC, huanmeng-qwq commented on src/main/java/snw/kookbc/impl/command/litecommands/StringHandler.java
> +        } catch (NullPointerException ignored) {
[LiteCommands#373](https://github.com/Rollczi/LiteCommands/pull/373) 修复 等待发版之后更改

2024-02-13 06:55 UTC, SNWCreations requested changes
需要修改。
此PR需要为draft状态。看起来并未完全完成。

2024-02-13 06:55 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/command/litecommands/StringHandler.java
> +            ((ConsoleCommandSender) sender).getLogger().info("命令 {} 的执行结果: {}", invocation.name(), result);
使用英语。

2024-02-13 06:55 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/command/litecommands/internal/PluginsCommand.java
> +/**
需要移除所有javadoc注释。
也许你可以对此项目禁用你的javadoc补全？
可以待PR内容大致完成后进行。

2024-02-13 07:01 UTC, SNWCreations commented
确认完成？开始审查。

2024-02-13 07:06 UTC, SNWCreations commented
通过。等待 @xiaoACE6716 审查。

2024-02-13 08:37 UTC, xiaoACE6716 reviewed
可以通过，但是是否应该将[KookOnlyConsoleContextual.java](https://github.com/SNWCreations/KookBC/pull/63/files#diff-52f56a34355c509fe8e00198fcb00b88401784815cbc7a360c8608947afbc27c) 中的 变量名onlyPlayerMessage 改为 onlyConsoleMessage 更好

2024-02-13 08:59 UTC, huanmeng-qwq commented
完成，可以合并，建议使用Squash。 @SNWCreations

2024-02-13 12:28 UTC, merged

2024-02-13 12:29 UTC, SNWCreations commented
合并完成。分支不建议删除。