Support Mixin framework
SNWCreations/KookBC pull request #8
Opened 2023-01-25 05:13 UTC by huanmeng-qwq

# KookBC Pull Request

您的 Fork 仓库地址: https://github.com/huanmeng-qwq/KookBC/

## 增加的新内容

对Mixin添加了支持，需要以Launch模式启动

## KookBC 程序的漏洞修复

修改了加载插件的顺序，现在loadPlugin将在core.init中创建SimplePluginManager后立即执行，enablePlugin被单独分成了一个方法在KBCClient#start方法调用

2023-01-25 05:49 UTC, SNWCreations requested changes
See details

2023-01-25 05:49 UTC, SNWCreations commented on pom.xml
> +        <dependency>
不应该这么修改，构建 KookBC 时应该直接从 JitPack 拉取工件。
你可能想在 API PR 完成后再修改这里？

2023-01-25 05:49 UTC, SNWCreations commented on src/main/java/snw/kookbc/Main.java
> +    public static class Main0 {
如果可以，请考虑分割类，尽可能减少 static 内部类的使用。
可以将这个类分割为package-private的，不可构造的类？

2023-01-25 05:49 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/launch/Launch.java
> +        //Get classpath
请在 '//' 后添加一个空格

2023-01-25 05:49 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/launch/LaunchClassLoader.java
> +import org.apache.logging.log4j.Level;
请尽可能使用 SLF4J 并减少对 Log4j2 的直接引用。

2023-01-25 05:49 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/mixin/KookBCServiceBootstrap.java
> +/**
KookBC 内部基本不使用 Javadoc ，可以改为 '//' 普通注释。

2023-01-25 05:53 UTC, huanmeng-qwq commented on src/main/java/snw/kookbc/Main.java
> +    public static class Main0 {
https://github.com/SNWCreations/KookBC/pull/8/commits/beb5b928e8b942aeac9133701a5205f4ee1674a5
已经修改了

2023-01-25 06:24 UTC, huanmeng-qwq commented on pom.xml
> +        <dependency>
在 API PR 完成后再修改这里

2023-01-27 08:09 UTC, SNWCreations commented
经过初步测试，未影响服务正常启动，正在准备装载一些插件以检查正常 JKook 插件的运行情况，另请在 KOOK 向我提供一个可以运行的 KookBC Mixin 插件。

2023-01-27 08:11 UTC, SNWCreations commented
追加问题：为何要在 KookBC 源代码中增加 MixinTransformer 的一个副本？

2023-01-27 08:43 UTC, SNWCreations commented
有一个报错：MixinBootstrap.doInit() called during a tweak constructor!
这是否会带来潜在问题？如果可能，请考虑修复。

2023-01-27 08:56 UTC, SNWCreations commented
我提交了一些“微小”的调整（我也不知道这是不是“微小”的），你可以看看我的修改是否会带来潜在威胁（我知道 Mixin 这种框架对类的加载很看重）

2023-01-27 09:14 UTC, SNWCreations commented
请为所有新增的文件增加版权声明，写在开头，原创的新类的话可以看其他已有版权声明的文件，若为复制的则请按照来源的许可协议增加声明

2023-01-27 09:23 UTC, SNWCreations commented
增加了一点文档更新，请拉取一下以获取最新内容，从而方便你的审阅

2023-01-27 09:45 UTC, SNWCreations commented
在控制台中测试发现了问题：TerminalConsoleAppender 似乎工作不正常。

2023-01-27 09:49 UTC, SNWCreations commented
可以考虑在合并前增加一个对 KookBC 进行了 Mixin 的插件的公开示例仓库？
这是可选项，可以选择不做。 :)

2023-01-27 10:27 UTC, huanmeng-qwq commented
> 可以考虑在合并前增加一个对 KookBC 进行了 Mixin 的插件的公开示例仓库？ 这是可选项，可以选择不做。 :)

https://github.com/huanmeng-qwq/KookBCMixinPluginExample

2023-01-27 10:42 UTC, SNWCreations commented
前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。

2023-01-27 11:18 UTC, huanmeng-qwq commented
> 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。

已修复，虽然不致命，但会导致Main类无法正常输出help信息:O

2023-01-27 13:04 UTC, SNWCreations commented
追加问题: sysout over slf4j 工作不正常

> > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> 
> 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O



> > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> 
> 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O

我明天试试换个实现 --help 的方法，请记得明天我出现在 KOOK 服务器的时候让我去改 lol

2023-01-27 14:48 UTC, huanmeng-qwq commented
> 



> 追加问题: sysout over slf4j 工作不正常 (你的 Mixin 插件是这样的)
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> 我明天试试换个实现 --help 的方法，请记得明天我出现在 KOOK 服务器的时候让我去改 lol

没能理解'sysout over slf4j 工作不正常'是怎么样的，可否提供一下相关代码，Mixin示例插件

> 追加问题: sysout over slf4j 工作不正常 (你的 Mixin 插件是这样的)
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> 我明天试试换个实现 --help 的方法，请记得明天我出现在 KOOK 服务器的时候让我去改 lol

已修复

2023-01-27 14:49 UTC, huanmeng-qwq commented
> 追加问题: sysout over slf4j 工作不正常 (你的 Mixin 插件是这样的)
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> > > 前面测试时遗留了一个问题: --help 命令行引起了 Mixin 的 ERROR 级问题，虽然不致命。
> > 
> > 
> > 已修复，虽然不致命，但会导致Main类无法正常输出help信息:O
> 
> 我明天试试换个实现 --help 的方法，请记得明天我出现在 KOOK 服务器的时候让我去改 lol

已修复

2023-01-28 00:44 UTC, SNWCreations requested changes
see details

2023-01-28 00:44 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/plugin/SimplePluginClassLoader.java
> +                client.getCore().getLogger().error(
为何认为这是一个错误？

2023-01-28 00:44 UTC, SNWCreations commented on src/main/java/snw/kookbc/impl/plugin/SimplePluginClassLoader.java
> +                        "[{}] {} v{} plugin is using the Mixin framework. Please use 'Launch' mode to enable support for Mixin",
建议增加新的一行log写"如果你通过正常的方式启动 KookBC 却得到了这个警告，那么这是一个 Bug !
因为 pom.xml 的 Main-Class 已经改为 LaunchMain 。

2023-01-28 06:39 UTC, SNWCreations approved these changes

2023-01-28 06:41 UTC, SNWCreations commented
请修复在高版本 Java VM 中无法启动的问题。
报错内容为 没有 Mixin 服务。
在 Java 11 (Alibaba Dragonwell)，Linux (gitpod.io 提供的虚拟机)下可以稳定复现。

2023-01-28 08:14 UTC, SNWCreations commented
LaunchMain 类没有版权声明。

2023-01-28 08:21 UTC, SNWCreations commented
请使用你的开发工具检查所有新增的文件，并按照开发工具的建议修改代码。
如 LaunchClassLoader 的构造方法中，classLoader参数从未使用。

2023-01-28 10:00 UTC, SNWCreations commented
ClassLoader#findClass 不可以返回 null ，你可能需要考虑 throw new ClassNotFoundException ?
* 然而这个建议存疑，因为既定事实是类已找到，但修改失败。

2023-01-28 10:15 UTC, huanmeng-qwq commented
> ClassLoader#findClass 不可以返回 null ，你可能需要考虑 throw new ClassNotFoundException ?
> 
> * 然而这个建议存疑，因为既定事实是类已找到，但修改失败。

感谢指出问题，一般是不会进入这个if判断的，但是return null确实存在一定的问题。

2023-01-29 01:44 UTC, SNWCreations commented
在 snw.kookbc.Main.main0 方法中找到了此PR最初提交时的一个残留变量: nonOptions ，它是否必要？如果不再必要，请移除。

2023-01-29 02:44 UTC, SNWCreations commented
snw.kookbc.impl.launch.Launch 与 snw.kookbc.LaunchMain 的区别在哪？经测试均可以启动 KookBC ，但 LaunchMain 指定了 MixinTweaker 。MixinTweaker 又扮演什么重要角色？

2023-01-29 07:03 UTC, huanmeng-qwq commented
LunachMain是对Launch的封装，也就可以在加载Lunch之前设置一些Property信息以及参数。
MixinTweaker可以理解Main的入口，其getLaunchTarget指向了Main，在加载完成后Lunach会执行该类的Main方法

2023-01-29 07:05 UTC, SNWCreations commented
如果可能，请尝试合并 LaunchMain 与 Launch 。

2023-01-29 08:09 UTC, SNWCreations commented
请检查所有新的代码，确认无误后，此PR就可以合并了。

2023-01-29 08:12 UTC, huanmeng-qwq commented
确认无误，现在可以合并了。

2023-01-29 08:22 UTC, merged

2023-01-29 08:22 UTC, SNWCreations commented
已完成。感谢贡献！

2023-01-29 08:32 UTC, SNWCreations commented
另请保留此fork分支，以便查看完整修改历史，便于回溯。